# -*- coding: utf-8 -*-
"""data_understanding_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3D29YbFFA9nGWrSPdP-w2RLSV-KaHSI
"""

# ====================================
# 01 - DATA UNDERSTANDING
# PROYECTO MACHINE LEARNING
# ====================================

from google.colab import files

# Subir archivo application_.parquet
uploaded = files.upload()

import pandas as pd
# Carga el dataset principal en formato Parquet
# Contiene informacion de las solicitudes de credito
app = pd.read_parquet("application_.parquet")

# Muestra la cantidad de filas y columnas del dataset
app.shape

# Analiza la distribucion de la variable TARGET
# Devuelve proporciones en lugar de conteos
app["TARGET"].value_counts(normalize=True)

# Calcula el porcentaje de valores nulos por columna
# Se ordena de mayor a menor para identificar las variables mas problematicas
app.isna().mean().sort_values(ascending=False).head(20)
