# -*- coding: utf-8 -*-
"""data_understanding_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3D29YbFFA9nGWrSPdP-w2RLSV-KaHSI
"""

# ====================================
# 01 - DATA UNDERSTANDING
# PROYECTO MACHINE LEARNING
# ====================================

from google.colab import files

# Subir archivo application_.parquet
uploaded = files.upload()

import pandas as pd

app = pd.read_parquet("application_.parquet")
app.shape

app["TARGET"].value_counts(normalize=True)

app.isna().mean().sort_values(ascending=False).head(20)