# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PH2GYUyIS0_GqeB29JrN-5JLWCAKiggo
"""

from google.colab import files

# Subir archivo full_dataset.parquet
uploaded = files.upload()


import pandas as pd
from lightgbm import LGBMClassifier
import joblib

# Carga del dataset completo con todas las features
df = pd.read_parquet("full_dataset.parquet")

X.dtypes[X.dtypes == "object"]

X = pd.get_dummies(X, drop_first=True)

# Limpiar nombres de columnas
X.columns = X.columns.str.replace(r'[^A-Za-z0-9_]+', '_', regex=True)

X = X.fillna(0)

model = LGBMClassifier(
    class_weight="balanced",
    random_state=42
)

model.fit(X, y)

# Guardado del modelo para la API
joblib.dump(model, "model.pkl")


# Descarga del modelo
from google.colab import files
files.download("model.pkl")
