# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0Na4fbEEkUgavh15XzzXQf6HdAg4A4w
"""

# ====================================
# 02 - FEATURE_ENGINEERING
# PROYECTO MACHINE LEARNING
# ====================================

from google.colab import files

# Subir archivos .parquet (Solamente application, burebau, previous_application, installments_payments, POS_CASH_balance)
uploaded = files.upload()

# Cargar Tablas

import pandas as pd

app = pd.read_parquet("application_.parquet")
bureau = pd.read_parquet("bureau.parquet")
prev = pd.read_parquet("previous_application.parquet")
inst = pd.read_parquet("installments_payments.parquet")
pos = pd.read_parquet("POS_CASH_balance.parquet")

bureau_agg = bureau.groupby("SK_ID_CURR").agg({
    "AMT_CREDIT_SUM": "sum",
    "AMT_CREDIT_SUM_DEBT": "sum",
    "DAYS_CREDIT": "mean"
}).reset_index()

prev_agg = prev.groupby("SK_ID_CURR").agg({
    "AMT_APPLICATION": "mean",
    "AMT_CREDIT": "mean",
    "CNT_PAYMENT": "mean"
}).reset_index()

inst["LATE_PAYMENT"] = inst["DAYS_ENTRY_PAYMENT"] - inst["DAYS_INSTALMENT"]

inst_agg = inst.groupby("SK_ID_CURR").agg({
    "LATE_PAYMENT": "mean",
    "AMT_PAYMENT": "mean"
}).reset_index()

pos_agg = pos.groupby("SK_ID_CURR").agg({
    "MONTHS_BALANCE": "mean",
    "CNT_INSTALMENT_FUTURE": "mean"
}).reset_index()

df = app.copy()

df = app.merge(bureau_agg, on="SK_ID_CURR", how="left")
df = df.merge(prev_agg, on="SK_ID_CURR", how="left")
df = df.merge(inst_agg, on="SK_ID_CURR", how="left")
df = df.merge(pos_agg, on="SK_ID_CURR", how="left")

df.to_parquet("full_dataset.parquet")

from google.colab import files

files.download("full_dataset.parquet")