# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0Na4fbEEkUgavh15XzzXQf6HdAg4A4w
"""

# ====================================
# 02 - FEATURE_ENGINEERING
# PROYECTO MACHINE LEARNING
# ====================================

from google.colab import files

# Subir archivos .parquet (Solamente application, burebau, previous_application, installments_payments, POS_CASH_balance)
uploaded = files.upload()

# Cargar Tablas

import pandas as pd

# Carga de las distintas tablas 
# Cada una aporta informacion distinta sobre el cliente
app = pd.read_parquet("application_.parquet")                # Dato actual de credito
bureau = pd.read_parquet("bureau.parquet")                   # Historial crediticio
prev = pd.read_parquet("previous_application.parquet")       # Solicitudes anteriores
inst = pd.read_parquet("installments_payments.parquet")      # Pagos de cuotas
pos = pd.read_parquet("POS_CASH_balance.parquet")            # Creditos de consumo


# Se resume la informacion para tener una fila por solicitante
bureau_agg = bureau.groupby("SK_ID_CURR").agg({
    "AMT_CREDIT_SUM": "sum",
    "AMT_CREDIT_SUM_DEBT": "sum",
    "DAYS_CREDIT": "mean"
}).reset_index()

# Agregacion de solicitudes de credito previas
# Analiza el comportamiento historico del cliente
prev_agg = prev.groupby("SK_ID_CURR").agg({
    "AMT_APPLICATION": "mean",
    "AMT_CREDIT": "mean",
    "CNT_PAYMENT": "mean"
}).reset_index()

inst["LATE_PAYMENT"] = inst["DAYS_ENTRY_PAYMENT"] - inst["DAYS_INSTALMENT"]

inst_agg = inst.groupby("SK_ID_CURR").agg({
    "LATE_PAYMENT": "mean",
    "AMT_PAYMENT": "mean"
}).reset_index()

pos_agg = pos.groupby("SK_ID_CURR").agg({
    "MONTHS_BALANCE": "mean",
    "CNT_INSTALMENT_FUTURE": "mean"
}).reset_index()

# Copia del dataset principal como base del dataset final
df = app.copy()

# Union de las tablas agregadas
df = app.merge(bureau_agg, on="SK_ID_CURR", how="left")
df = df.merge(prev_agg, on="SK_ID_CURR", how="left")
df = df.merge(inst_agg, on="SK_ID_CURR", how="left")
df = df.merge(pos_agg, on="SK_ID_CURR", how="left")

# Guardado del dataset final con todas las features generadas
df.to_parquet("full_dataset.parquet")

from google.colab import files

files.download("full_dataset.parquet")
